name: Mi primera Integracion Continua

on:
  pull_request:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: configurar el gradle
        uses: gradle/gradle-build-action@v2
      - name: usar el gradle para compilar
        run: ./gradlew build